# This is a basic workflow to help you get started with Actions

name: BuildAndUploadImages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.2
      with:
          versionSpec: '5.2.x'
    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.2
    - name: Set build script eXecutable
      id: builscriptexec
      run: chmod +x ./build.sh
    - name: Build ARM container
      id: armcontainer
      run: ./build.sh -Target PushArmDockerContainer -DockerPrivateRegistry "${{ secrets.DOCKER_REGISTRY }}" -DockerLogin "${{ secrets.DOCKER_REGISTRY_LOGIN }}" -DockerPassword "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" -BuildVersion "${{ steps.gitversion.outputs.majorMinorPatch }}"
    - name: Build x64 container
      id: x64container
      run: ./build.sh -Target PushDockerContainer -DockerPrivateRegistry "${{ secrets.DOCKER_REGISTRY }}" -DockerLogin "${{ secrets.DOCKER_REGISTRY_LOGIN }}" -DockerPassword "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" -BuildVersion "${{ steps.gitversion.outputs.majorMinorPatch }}"
